version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:80"
    # Remove volumes to avoid overwriting vendor inside container
    # volumes:
    #   - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
